# Generated by Django 5.2.7 on 2025-11-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.userprofile'),
        ),
    ]
