# Generated by Django 5.2.7 on 2025-11-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
