# Generated by Django 5.2.7 on 2025-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('tech', 'Technology'), ('health', 'Health'), ('edu', 'Education'), ('sports', 'Sports'), ('ent', 'Entertainment'), ('science', 'Science'), ('travel', 'Travel'), ('food', 'Food'), ('fashion', 'Fashion'), ('business', 'Business')], default='All', max_length=200),
        ),
    ]
